<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="jakarta.tags.core" %>
<!DOCTYPE html><html lang="vi"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title><sitemesh:write property="title"/> - VideoHub</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" rel="stylesheet"><sitemesh:write property="head"/>
<style>body{background:#f1f5f9;color:#0f172a}.site-header{background:#fff;border-bottom:1px solid #e2e8f0}.brand{font-size:22px;font-weight:800;color:#2563eb;text-decoration:none}.site-main{min-height:calc(100vh - 170px)}.site-footer{background:#1f2937;color:#fff}.nav-link{font-weight:600}</style></head><body>
<header class="site-header sticky-top"><nav class="navbar navbar-expand-lg"><div class="container"><a class="brand" href="${pageContext.request.contextPath}/home"><i class="bi bi-play-btn-fill"></i> VideoHub</a><button class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#menu"><span class="navbar-toggler-icon"></span></button>
<div class="collapse navbar-collapse" id="menu"><ul class="navbar-nav ms-auto align-items-lg-center gap-lg-2"><li class="nav-item"><a class="nav-link" href="${pageContext.request.contextPath}/home">Trang chủ</a></li><li class="nav-item"><a class="nav-link" href="${pageContext.request.contextPath}/home">Sản phẩm</a></li>
<c:if test="${not empty sessionScope.account and sessionScope.account.admin}"><li class="nav-item"><a class="nav-link text-primary" href="${pageContext.request.contextPath}/admin/home">Trang quản trị</a></li></c:if>
<li class="nav-item"><a class="nav-link position-relative" href="${pageContext.request.contextPath}/cart" title="Giỏ hàng"><i class="bi bi-cart3 fs-5"></i><c:if test="${not empty sessionScope.cart and not empty sessionScope.cart.values()}"><span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger" style="font-size: 0.65rem;">${sessionScope.cart.size()}</span></c:if></a></li>
<c:choose><c:when test="${empty sessionScope.account}"><li><a class="btn btn-primary btn-sm" href="${pageContext.request.contextPath}/login">Đăng nhập</a></li></c:when><c:otherwise><li class="nav-item"><a class="nav-link" href="${pageContext.request.contextPath}/orders"><i class="bi bi-clock-history me-1"></i>Lịch sử đơn</a></li><li class="nav-item"><span class="nav-link text-primary fw-bold">${sessionScope.account.fullname}</span></li><li><a class="btn btn-outline-danger btn-sm" href="${pageContext.request.contextPath}/logout">Đăng xuất</a></li></c:otherwise></c:choose></ul></div></div></nav></header>
<main class="site-main"><sitemesh:write property="body"/></main>
<footer class="site-footer py-3 mt-4"><div class="container text-center">Họ và tên: <strong>Lâm Huy Bách</strong> &nbsp;|&nbsp; MSSV: <strong>24110165</strong> &nbsp;|&nbsp; Mã đề: <strong>Đề số 3</strong></div></footer>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script></body></html>
